spring.application.name=backend

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/offline_todo}
spring.datasource.username=${DATABASE_USERNAME:offline_todo}
spring.datasource.password=${DATABASE_PASSWORD:offline_todo_dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
